name: InferSharp
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  infer:
    runs-on: ubuntu-latest
    steps:
      - name: Run Infer#
        uses: microsoft/infersharpaction@v1.2.1
        id: runinfersharp
        with:
          binary-path: 'src/'

      - name: Upload SARIF output to GitHub Security Center
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: infer-out/report.sarif